# Generated by Django 3.2 on 2023-12-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_confirmation_code'),
        ('users', '0005_user_confirmation_code'),
    ]

    operations = [
    ]
