# Generated by Django 3.2 on 2023-12-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.PositiveIntegerField(default=1, verbose_name='Рейтинг произведений'),
            preserve_default=False,
        ),
    ]
