# Generated by Django 3.2 on 2023-11-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231129_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ТекстВР')),
            ],
            options={
                'verbose_name': 'произведениеВР',
                'verbose_name_plural': 'ПроизведенияВР',
            },
        ),
    ]
