# Generated by Django 3.2 on 2023-12-11 06:03

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20231209_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[reviews.models.validate_year], verbose_name='Год произведения'),
        ),
    ]
