# Generated by Django 3.2 on 2023-12-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20231204_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='author',
        ),
        migrations.RemoveField(
            model_name='title',
            name='author',
        ),
    ]
