# Generated by Django 3.2 on 2023-11-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_title'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='review',
#            name='author',
#        ),
#        migrations.RemoveField(
#            model_name='review',
#            name='title',
#        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
