# Generated by Django 3.2 on 2023-12-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveIntegerField(null=True, verbose_name='Рейтинг произведений'),
        ),
    ]
