# Generated by Django 3.2 on 2023-12-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_genre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
    ]
